name: flutter_awesome_context_menu_examples
description: "A Flutter package that provides a customizable context menu for Flutter applications. This example demonstrates how to use the flutter_awesome_context_menu package."
publish_to: 'none' #Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_awesome_context_menu:
    path: ../
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
