name: flutter_awesome_context_menu
description: "A Flutter package that provides a browser-like right-click context menu."
version: 0.0.1
homepage: https://github.com/sequ3l/flutter_awesome_context_menu

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
